In [1]:
# Numpy (numerical python)
# is a open source python library widely used in data science / machine learning / gen AI.
# it provides powerful N dimensional array data structure.
# most efficient and fastest library in python
# why it is fast - underlying is C pre - compiled code

# numpy is ndarray object - which represents a homogenous N dimentional array of items

In [3]:
# numpy is a module which needs to be imported
# pip install numpy
import numpy as np

In [4]:
# 1 D array
a = np.array([2, 4, 6, 8, 10])

In [9]:
print(a)
print(a[2])

[ 2  4  6  8 10]
6


In [7]:
# 2 D array
b = np.array([[1, 11, 111, 1111], [21, 22, 23, 24], [31, 32, 33, 34]])
print(b)

[[   1   11  111 1111]
 [  21   22   23   24]
 [  31   32   33   34]]


In [8]:
# accessing a numpy array element
print(b[1, 3])

24


In [11]:
# modifying an element i.e numpy arrays are mutable
b[1, 3] = 200
print(b)

[[   1   11  111 1111]
 [  21   22   23  200]
 [  31   32   33   34]]


In [12]:
# slicing
# same python slicing (i.e list, string) works with numpy
# there is key diference between python slicing and numpy slicing
# python list slicing -  returns a copy
# numpy slicing - returns a view of the original data

a = np.array([10, 20, 30, 40, 50])
print(a[:3])

[10 20 30]


In [13]:
b = a[:3]
print(b)


[10 20 30]


In [14]:
b[0] = 1000
print(b)

[1000   20   30]


In [15]:
print(a)

[1000   20   30   40   50]


In [20]:
# Numpy Attributes
# ndim - number of dimensions
# shape - returns a tuple / size of the array along each dimension
# size - total number of element in the array
# dtype - data type of numpy array

a = np.array([1, 2, 3, 4])
print(f"Dimension (ndim): {a.ndim}")
print(f"Shape : {a.shape}")
print(f"Size : {a.size}")
print(f"Data type : {a.dtype}")

Dimension (ndim): 1
Shape : (4,)
Size : 4
Data type : int64


In [22]:
a = np.array([[1, 2, 3, 4], [21, 22, 23, 24], [31, 32, 33, 34], [41, 42, 43, 44]])
print(f"Dimension (ndim): {a.ndim}")
print(f"Shape : {a.shape}")
print(f"Size : {a.size}")
print(f"Data type : {a.dtype}")

Dimension (ndim): 2
Shape : (4, 4)
Size : 16
Data type : int64


In [23]:
# Numpy has inbuilt function to create a array with initial values
a = np.zeros(2)
print(a)

[0. 0.]


In [24]:
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [27]:
a = np.empty(4)
print(a)

[1. 1. 1. 1.]


In [29]:
# arange - creates an aray with a range of element
a = np.arange(2, 9, 2)
print(a)

[2 4 6 8]


In [30]:
# sorting and concatination
a = np.array([210, 20, 3, 410, 150])
print(np.sort(a))

[  3  20 150 210 410]


In [32]:
a = np.array([210, 20, 3, 410, 150])
b = np.array([1210, 120, 13, 1410, 1150])
print(np.concatenate((a, b)))

[ 210   20    3  410  150 1210  120   13 1410 1150]


In [38]:
# conditional indexing / vectorizaion example
b = np.array([[1, 11, 111, 1111], [21, 22, 23, 24], [31, 32, 33, 34]])
print(b[b > 100])
print(b[b % 2 == 0])
print(b[(b > 25) & (b < 100)])

[ 111 1111]
[22 24 32 34]
[31 32 33 34]


In [40]:
# copy
a = np.array([210, 20, 3, 410, 150])
a2 = a.copy()
print(a2)
a2[2] = 3000
print(a2)
print(a)

[210  20   3 410 150]
[ 210   20 3000  410  150]
[210  20   3 410 150]


In [41]:
# Array Operation 
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print(a + b)

[ 2  4  6  8 10]


In [42]:
print(a * b)

[ 1  4  9 16 25]


In [43]:
# aggregate function - sum(), min(), max(), stddev()

In [48]:
# Broadcasting
# it allows numpy to [perform operation on arrays with different shapes by virtually expanding dimensions

a = np.array([[1, 2, 3, 4, 5],
             [11, 12, 13, 14, 15]])

#b = np.array([1, 2, 3, 4, 5])
b = np.array([10])

print(a.shape)
print(b.shape)

print(a + b)

(2, 5)
(1,)
[[11 12 13 14 15]
 [21 22 23 24 25]]
